STOCKS_INDEX_NAME = {
    "AAPL": "Apple",
    "MSFT": "Microsoft",
    "AMZN": "Amazon",
    "NVDA": "Nvidia",
    "GOOGL": "Alphabet",
    "GOOG": "Alphabet",
    "META": "Meta",
    "BRKB": "Berkshire Hathaway",
    "TSLA": "Tesla",
    "UNH": "Unitedhealth",
    "LLY": "Eli Lilly",
    "JPM": "JPMorgan Chase & Co",
    "XOM": "Exxon Mobil",
    "JNJ": "Johnson & Johnson",
    "V": "Visa",
    "PG": "Procter & Gamble",
    "AVGO": "Broadcom",
    "MA": "Mastercard",
    "HD": "Home Depot",
    "CVX": "Chevron",
    "MRK": "Merck & Co",
    "ABBV": "Abbvie",
    "PEP": "Pepsico",
    "COST": "Costco Wholesale",
    "ADBE": "Adobe",
    "KO": "Coca-Cola",
    "CSCO": "Cisco Systems",
    "WMT": "Walmart",
    "TMO": "Thermo Fisher Scientific",
    "MCD": "Mcdonalds",
    "PFE": "Pfizer",
    "CRM": "Salesforce",
    "BAC": "Bank Of America",
    "ACN": "Accenture Plc",
    "CMCSA": "Comcast",
    "LIN": "Linde Plc",
    "NFLX": "Netflix",
    "ABT": "Abbott Laboratories",
    "ORCL": "Oracle",
    "DHR": "Danaher",
    "AMD": "Advanced Micro Devices",
    "WFC": "Wells Fargo",
    "DIS": "Walt Disney",
    "TXN": "Texas Instrument",
    "PM": "Philip Morris International",
    "VZ": "Verizon Communications",
    "INTU": "Intuit",
    "COP": "Conocophillips",
    "CAT": "Caterpillar",
    "AMGN": "Amgen",
    "NEE": "Nextera Energy",
    "INTC": "Intel",
    "UNP": "Union Pacific",
    "LOW": "Lowes Companies",
    "IBM": "International Business Machines Co",
    "BMY": "Bristol Myers Squibb",
    "SPGI": "S&P Global",
    "RTX": "Rtx",
    "HON": "Honeywell International",
    "BA": "Boeing",
    "UPS": "United Parcel Service",
    "GE": "General Electric",
    "QCOM": "Qualcomm",
    "AMAT": "Applied Material",
    "NKE": "Nike",
    "PLD": "Prologis Reit",
    "NOW": "Servicenow",
    "BKNG": "Booking Holdings",
    "SBUX": "Starbucks",
    "MS": "Morgan Stanley",
    "ELV": "Elevance Health",
    "MDT": "Medtronic Plc",
    "GS": "Goldman Sachs",
    "DE": "Deere",
    "ADP": "Automatic Data Processing",
    "LMT": "Lockheed Martin",
    "TJX": "TJX",
    "T": "At&T",
    "BLK": "Blackrock",
    "ISRG": "Intuitive Surgical",
    "MDLZ": "Mondelez International",
    "GILD": "Gilead Sciences",
    "MMC": "Marsh & Mclennan",
    "AXP": "American Express",
    "SYK": "Stryker",
    "REGN": "Regeneron Pharmaceuticals",
    "VRTX": "Vertex Pharmaceuticals",
    "ETN": "Eaton Plc",
    "LRCX": "Lam Research",
    "ADI": "Analog Devices",
    "SCHW": "Charles Schwab",
    "CVS": "CVS Health",
    "ZTS": "Zoetis",
    "CI": "Cigna",
    "CB": "Chubb Ltd",
    "AMT": "American Tower Reit",
    "SLB": "Schlumberger Nv",
    "C": "Citigroup",
    "BDX": "Becton Dickinson",
    "MO": "Altria",
    "PGR": "Progressive",
    "TMUS": "T Mobile Us",
    "FI": "Fiserv",
    "SO": "Southern",
    "EOG": "EOG Resources",
    "BSX": "Boston Scientific",
    "CME": "CME",
    "EQIX": "Equinix Reit",
    "MU": "Micron Technology",
    "DUK": "Duke Energy",
    "PANW": "Palo Alto Networks",
    "PYPL": "Paypal Holdings",
    "AON": "Aon Plc",
    "SNPS": "Synopsys",
    "ITW": "Illinois Tool",
    "KLAC": "Kla",
    "LULU": "Lululemon Athletica",
    "ICE": "Intercontinental Exchange",
    "APD": "Air Products And Chemicals",
    "SHW": "Sherwin Williams",
    "CDNS": "Cadence Design Systems",
    "CSX": "CSX",
    "NOC": "Northrop Grumman",
    "CL": "Colgate-Palmolive",
    "MPC": "Marathon Petroleum",
    "HUM": "Humana",
    "FDX": "Fedex",
    "WM": "Waste Management",
    "MCK": "Mckesson",
    "TGT": "Target",
    "ORLY": "Oreilly Automotive",
    "HCA": "HCA Healthcare",
    "FCX": "Freeport Mcmoran",
    "EMR": "Emerson Electric",
    "PXD": "Pioneer Natural Resource",
    "MMM": "3M",
    "MCO": "Moodys",
    "ROP": "Roper Technologies",
    "CMG": "Chipotle Mexican Grill",
    "PSX": "Phillips",
    "MAR": "Marriott International",
    "PH": "Parker-Hannifin",
    "APH": "Amphenol",
    "GD": "General Dynamics",
    "USB": "US Ba",
    "NXPI": "NXP Semiconductors NV",
    "AJG": "Arthur J Gallagher",
    "NSC": "Norfolk Southern",
    "PNC": "Pnc Financial Services",
    "VLO": "Valero Energy",
    "F": "Ford Motor Co",
    "MSI": "Motorola Solutions",
    "GM": "General Motors",
    "TT": "Trane Technologies Plc",
    "EW": "Edwards Lifesciences",
    "CARR": "Carrier Global",
    "AZO": "Autozone",
    "ADSK": "Autodesk",
    "TDG": "Transdigm",
    "ANET": "Arista Networks",
    "SRE": "Sempra",
    "ECL": "Ecolab",
    "OXY": "Occidental Petroleum",
    "PCAR": "Paccar",
    "ADM": "Archer Daniels Midland",
    "MNST": "Monster Beverage",
    "KMB": "Kimberly Clark",
    "PSA": "Public Storage Reit",
    "CCI": "Crown Castle",
    "CHTR": "Charter Communications",
    "MCHP": "Microchip Technology",
    "MSCI": "MSCI",
    "CTAS": "Cintas",
    "WMB": "Williams",
    "AIG": "American International",
    "STZ": "Constellation Brands",
    "HES": "Hess",
    "NUE": "Nucor",
    "ROST": "Ross Stores",
    "AFL": "Aflac",
    "KVUE": "Kenvue",
    "AEP": "American Electric Power",
    "IDXX": "Idexx Laboratories",
    "D": "Dominion Energy",
    "TEL": "Te Connectivity Ltd",
    "JCI": "Johnson Controls International Plc",
    "MET": "Metlife",
    "GIS": "General Mills",
    "IQV": "Iqvia Holdings",
    "EXC": "Exelon",
    "WELL": "Welltower",
    "DXCM": "Dexcom",
    "HLT": "Hilton Worldwide Holdings",
    "ON": "On Semiconductor",
    "COF": "Capital One Financial",
    "PAYX": "Paychex",
    "TFC": "Truist Financial",
    "BIIB": "Biogen",
    "O": "Realtyome Reit",
    "FTNT": "Fortinet",
    "DOW": "Dow",
    "TRV": "Travelers Companies",
    "DLR": "Digital Realty Trust Reit",
    "MRNA": "Moderna",
    "CPRT": "Copart",
    "ODFL": "Old Dominion Freight Line",
    "DHI": "D R Horton",
    "YUM": "Yum Brands",
    "SPG": "Simon Property Group Reit",
    "CTSH": "Cognizant Technology Solutions Cor",
    "AME": "Ametek",
    "BKR": "Baker Hughes",
    "SYY": "Sysco",
    "A": "Agilent Technologies",
    "CTVA": "Corteva",
    "CNC": "Centene",
    "EL": "Estee Lauder",
    "AMP": "Ameriprise Finance",
    "CEG": "Constellation Energy",
    "HAL": "Halliburton",
    "OTIS": "Otis Worldwide",
    "ROK": "Rockwell Automation",
    "PRU": "Prudential Financial",
    "DD": "Dupont De Nemours",
    "KMI": "Kinder Morgan",
    "VRSK": "Verisk Analytics",
    "LHX": "L3Harris Technologies",
    "DG": "Dollar General",
    "FIS": "Fidelity National Information Serv",
    "CMI": "Cummins",
    "CSGP": "Costar Group",
    "FAST": "Fastenal",
    "PPG": "PPG Industries",
    "GPN": "Global Payments",
    "GWW": "WW Grainger",
    "HSY": "Hershey Foods",
    "BK": "Bank Of New York Mellon",
    "XEL": "Xcel Energy",
    "DVN": "Devon Energy",
    "EA": "Electronic Arts",
    "NEM": "Newmont",
    "ED": "Consolidated Edison",
    "URI": "United Rentals",
    "VICI": "Vici Pptys",
    "PEG": "Public Service Enterprise Group In",
    "KR": "Kroger",
    "RSG": "Republic Services",
    "LEN": "Lennar A",
    "PWR": "Quanta Services",
    "WST": "West Pharmaceutical Services",
    "COR": "Cencora",
    "OKE": "Oneok",
    "VMC": "Vulcan Materials",
    "KDP": "Keurig Dr Pepper",
    "WBD": "Warner Bros. Discovery Series",
    "ACGL": "Arch Capital Group Ltd",
    "ALL": "Allstate",
    "IR": "Ingersoll Rand",
    "CDW": "Cdw",
    "FANG": "Diamondback Energy",
    "MLM": "Martin Marietta Materials",
    "PCG": "Pg&E",
    "DAL": "Delta Air Lines",
    "EXR": "Extra Space Storage Reit",
    "FTV": "Fortive",
    "AWK": "American Water Works",
    "IT": "Gartner",
    "KHC": "Kraft Heinz",
    "GEHC": "Ge Healthcare Technologies",
    "WEC": "Wec Energy Group",
    "HPQ": "Hp",
    "EIX": "Edison International",
    "CBRE": "Cbre Group",
    "APTV": "Aptiv Plc",
    "ANSS": "Ansys",
    "MTD": "Mettler Toledo",
    "DLTR": "Dollar Tree",
    "AVB": "Avalonbay Communities Reit",
    "ILMN": "Illumina",
    "ALGN": "Align Technology",
    "LYB": "Lyondellbasell Industries Nv Class",
    "TROW": "T Rowe Price Group",
    "GLW": "Corning",
    "EFX": "Equifax",
    "WY": "Weyerhaeuser Reit",
    "ZBH": "Zimmer Biomet Holdings",
    "XYL": "Xylem",
    "SBAC": "Sba Communications Reit",
    "RMD": "Resmed",
    "TSCO": "Tractor Supply",
    "EBAY": "Ebay",
    "KEYS": "Keysight Technologies",
    "CHD": "Church And Dwight",
    "STT": "State Street",
    "DFS": "Discover Financial Services",
    "HIG": "Hartford Financial Services Group",
    "ALB": "Albemarle",
    "STE": "Steris",
    "ES": "Eversource Energy",
    "TTWO": "Take Two Interactive Software",
    "MPWR": "Monolithic Power Systems",
    "CAH": "Cardinal Health",
    "EQR": "Equity Residential Reit",
    "RCL": "Royal Caribbean Group Ltd",
    "WTW": "Willis Towers Watson Plc",
    "HPE": "Hewlett Packard Enterprise",
    "DTE": "Dte Energy",
    "GPC": "Genuine Parts",
    "BR": "Broadridge Financial Solutions",
    "ULTA": "Ulta Beauty",
    "FICO": "Fair Isaac",
    "CTRA": "Coterra Energy",
    "BAX": "Baxter International",
    "AEE": "Ameren",
    "MTB": "M&T Bank",
    "MKC": "Mccormick & Co Non-Voting",
    "ETR": "Entergy",
    "WAB": "Westinghouse Air Brake Technologies",
    "DOV": "Dover",
    "FE": "Firstenergy",
    "RJF": "Raymond James",
    "INVH": "Invitation Homes",
    "FLT": "Fleetcor Technologies",
    "CLX": "Clorox",
    "TDY": "Teledyne Technologies",
    "TRGP": "Targa Resources",
    "DRI": "Darden Restaurants",
    "LH": "Laboratory corporation",
    "HOLX": "Hologic",
    "VRSN": "Verisign",
    "MOH": "Molina Healthcare",
    "LUV": "Southwest Airlines",
    "PPL": "PPL",
    "ARE": "Alexandria Real Estate Equities Reit",
    "NVR": "Nvr",
    "COO": "Cooper",
    "WBA": "Walgreen Boots Alliance",
    "PHM": "Pultegroup",
    "NDAQ": "Nasdaq",
    "HWM": "Howmet Aerospace",
    "RF": "Regions Financial",
    "CNP": "Centerpoint Energy",
    "IRM": "Iron Mountain",
    "LVS": "Las Vegas Sands",
    "FITB": "Fifth Third Bancorp",
    "EXPD": "Expeditors International Of Washington",
    "VTR": "Ventas Reit",
    "FSLR": "First Solar",
    "PFG": "Pincipal Financial Group",
    "BRO": "Brown & Brown",
    "J": "Jacobs Solutions",
    "IEX": "Idex",
    "BG": "Bunge Ltd",
    "ATO": "Atmos Energy",
    "FDS": "Factset Research Systems",
    "ENPH": "Enphase Energy",
    "MAA": "Mid America Apartment Communities",
    "CMS": "Cms Energy",
    "IFF": "International Flavors & Fragrances",
    "BALL": "Ball",
    "SWKS": "Skyworks Solutions",
    "CINF": "Cincinnati Financial",
    "NTAP": "Netapp",
    "STLD": "Steel Dynamics",
    "UAL": "United Airlines Holdings",
    "WAT": "Waters",
    "OMC": "Omnicom Group",
    "TER": "Teradyne",
    "CCL": "Carnival",
    "JBHT": "JB Hunt Transport Services",
    "MRO": "Marathon Oil",
    "TYL": "Tyler Technologies",
    "HBAN": "Huntington Bancshares",
    "K": "Kellogg",
    "GRMN": "Garmin Ltd",
    "CBOE": "Cboe Global Markets",
    "NTRS": "Northern Trust",
    "TSN": "Tyson Foods",
    "AKAM": "Akamai Technologies",
    "EG": "Everest Group Ltd",
    "ESS": "Essex Property Trust Reit",
    "EQT": "Eqt",
    "TXT": "Textron",
    "EXPE": "Expedia Group",
    "SJM": "Jm Smucker",
    "PTC": "Ptc",
    "DGX": "Quest Diagnostics",
    "AVY": "Avery Dennison",
    "RVTY": "Revvity",
    "BBY": "Best Buy Co",
    "CF": "Cf Industries Holdings",
    "CAG": "Conagra Brands",
    "EPAM": "Epam Systems",
    "AMCR": "Amcor Plc",
    "LW": "Lamb Weston Holdings",
    "PAYC": "Paycom Software",
    "SNA": "Snap On",
    "AXON": "Axon Enterprise",
    "POOL": "Pool",
    "SYF": "Synchrony Financial",
    "SWK": "Stanley Black & Decker",
    "ZBRA": "Zebra Technologies",
    "DPZ": "Dominos Pizza",
    "PKG": "Packaging Corp Of America",
    "CFG": "Citizens Financial Group",
    "LDOS": "Leidos Holdings",
    "VTRS": "Viatris",
    "PODD": "Insulet",
    "LKQ": "LKQ",
    "MOS": "Mosaic",
    "APA": "APA",
    "EVRG": "Evergy",
    "TRMB": "Trimble",
    "MGM": "Mgm Resorts International",
    "NDSN": "Nordson",
    "WDC": "Western Digital",
    "MAS": "Masco",
    "LNT": "Alliant Energy",
    "IPG": "Interpublic Group Of Companies",
    "MTCH": "Match Group",
    "STX": "Seagate Technology Holdings Plc",
    "KMX": "Carmax",
    "TECH": "Bio Techne",
    "WRB": "WR Berkley",
    "BFB": "Brown Forman",
    "LYV": "Live Nation Entertainment",
    "IP": "International Paper",
    "UDR": "UDR Reit",
    "AES": "AES",
    "CE": "Celanese",
    "INCY": "Incyte",
    "L": "Loews",
    "TAP": "Molson Coors Brewing",
    "GEN": "Gen Digital",
    "CPT": "Camden Property Trust Reit",
    "KIM": "Kimco Realty Reit",
    "JKHY": "Jack Henry And Associates",
    "HRL": "Hormel Foods",
    "HST": "Host Hotels & Resorts Reit",
    "FMC": "FMC",
    "CZR": "Caesars Entertainment",
    "PEAK": "Healthpeak Properties",
    "CDAY": "Ceridian Hcm Holding",
    "PNR": "Pentair",
    "NI": "Nisource",
    "CHRW": "Ch Robinson Worldwide",
    "HSIC": "Henry Schein",
    "CRL": "Charles River Laboratories International",
    "REG": "Regency Centers Reit",
    "QRVO": "Qorvo",
    "TFX": "Teleflex",
    "KEY": "Keycorp",
    "GL": "Globe Life",
    "EMN": "Eastman Chemical",
    "WYNN": "Wynn Resorts Ltd",
    "ALLE": "Allegion Plc",
    "AAL": "American Airlines Group",
    "FFIV": "F5",
    "BWA": "Borgwarner",
    "BXP": "Boston Properties Reit",
    "MKTX": "Marketaxess Holdings",
    "ROL": "Rollins",
    "JNPR": "Juniper Networks",
    "PNW": "Pinnacle West",
    "ETSY": "Etsy",
    "BLDR": "Builders FirstSource.",
    "FOXA": "Fox",
    "AOS": "A O Smith",
    "HAS": "Hasbro",
    "HII": "Huntington Ingalls Industries",
    "NRG": "Nrg Energy",
    "CPB": "Campbell Soup",
    "UHS": "Universal Health Services",
    "BIO": "Bio Rad Laboratories",
    "WRK": "Westrock",
    "RHI": "Robert Half",
    "CTLT": "Catalent",
    "GEV": "GE Vernova",
    "BBWI": "Bath And Body Works",
    "NWSA": "News",
    "TPR": "Tapestry",
    "PARA": "Paramount Global",
    "SMCI": "Super Micro Computer",
    "BEN": "Franklin Resources",
    "AIZ": "Assurant",
    "NCLH": "Norwegian Cruise Line Holdings Ltd",
    "GNRC": "Generac Holdings",
    "FRT": "Federal Realty Investment Trust Reit",
    "IVZ": "Invesco Ltd",
    "SOLV": "Solventum",
    "CMA": "Comerica",
    "DVA": "Davita",
    "JBL": "Jabil",
    "HUBB": "Hubbell",
    "DECK": "Deckers",
    "UBER": "Uber",
    "MHK": "Mohawk",
    "RL": "Ralph Lauren",
    "VLTO": "Veralto",
    "FOX": "Fox",
    "BX": "Blackstone",
    "ABNB": "Airbnb",
    "NWS": "News"
}

STOCKS_INDEX_SENTIMENT = {
    "AAPL": 0,
    "MSFT": 0,
    "AMZN": 0,
    "NVDA": 0,
    "GOOGL": 0,
    "GOOG": 0,
    "META": 0,
    "BRKB": 0,
    "TSLA": 0,
    "UNH": 0,
    "LLY": 0,
    "JPM": 0,
    "XOM": 0,
    "JNJ": 0,
    "V": 0,
    "PG": 0,
    "AVGO": 0,
    "MA": 0,
    "HD": 0,
    "CVX": 0,
    "MRK": 0,
    "ABBV": 0,
    "PEP": 0,
    "COST": 0,
    "ADBE": 0,
    "KO": 0,
    "CSCO": 0,
    "WMT": 0,
    "TMO": 0,
    "MCD": 0,
    "PFE": 0,
    "CRM": 0,
    "BAC": 0,
    "ACN": 0,
    "CMCSA": 0,
    "LIN": 0,
    "NFLX": 0,
    "ABT": 0,
    "ORCL": 0,
    "DHR": 0,
    "AMD": 0,
    "WFC": 0,
    "DIS": 0,
    "TXN": 0,
    "PM": 0,
    "VZ": 0,
    "INTU": 0,
    "COP": 0,
    "CAT": 0,
    "AMGN": 0,
    "NEE": 0,
    "INTC": 0,
    "UNP": 0,
    "LOW": 0,
    "IBM": 0,
    "BMY": 0,
    "SPGI": 0,
    "RTX": 0,
    "HON": 0,
    "BA": 0,
    "UPS": 0,
    "GE": 0,
    "QCOM": 0,
    "AMAT": 0,
    "NKE": 0,
    "PLD": 0,
    "NOW": 0,
    "BKNG": 0,
    "SBUX": 0,
    "MS": 0,
    "ELV": 0,
    "MDT": 0,
    "GS": 0,
    "DE": 0,
    "ADP": 0,
    "LMT": 0,
    "TJX": 0,
    "T": 0,
    "BLK": 0,
    "ISRG": 0,
    "MDLZ": 0,
    "GILD": 0,
    "MMC": 0,
    "AXP": 0,
    "SYK": 0,
    "REGN": 0,
    "VRTX": 0,
    "ETN": 0,
    "LRCX": 0,
    "ADI": 0,
    "SCHW": 0,
    "CVS": 0,
    "ZTS": 0,
    "CI": 0,
    "CB": 0,
    "AMT": 0,
    "SLB": 0,
    "C": 0,
    "BDX": 0,
    "MO": 0,
    "PGR": 0,
    "TMUS": 0,
    "FI": 0,
    "SO": 0,
    "EOG": 0,
    "BSX": 0,
    "CME": 0,
    "EQIX": 0,
    "MU": 0,
    "DUK": 0,
    "PANW": 0,
    "PYPL": 0,
    "AON": 0,
    "SNPS": 0,
    "ITW": 0,
    "KLAC": 0,
    "LULU": 0,
    "ICE": 0,
    "APD": 0,
    "SHW": 0,
    "CDNS": 0,
    "CSX": 0,
    "NOC": 0,
    "CL": 0,
    "MPC": 0,
    "HUM": 0,
    "FDX": 0,
    "WM": 0,
    "MCK": 0,
    "TGT": 0,
    "ORLY": 0,
    "HCA": 0,
    "FCX": 0,
    "EMR": 0,
    "PXD": 0,
    "MMM": 0,
    "MCO": 0,
    "ROP": 0,
    "CMG": 0,
    "PSX": 0,
    "MAR": 0,
    "PH": 0,
    "APH": 0,
    "GD": 0,
    "USB": 0,
    "NXPI": 0,
    "AJG": 0,
    "NSC": 0,
    "PNC": 0,
    "VLO": 0,
    "F": 0,
    "MSI": 0,
    "GM": 0,
    "TT": 0,
    "EW": 0,
    "CARR": 0,
    "AZO": 0,
    "ADSK": 0,
    "TDG": 0,
    "ANET": 0,
    "SRE": 0,
    "ECL": 0,
    "OXY": 0,
    "PCAR": 0,
    "ADM": 0,
    "MNST": 0,
    "KMB": 0,
    "PSA": 0,
    "CCI": 0,
    "CHTR": 0,
    "MCHP": 0,
    "MSCI": 0,
    "CTAS": 0,
    "WMB": 0,
    "AIG": 0,
    "STZ": 0,
    "HES": 0,
    "NUE": 0,
    "ROST": 0,
    "AFL": 0,
    "KVUE": 0,
    "AEP": 0,
    "IDXX": 0,
    "D": 0,
    "TEL": 0,
    "JCI": 0,
    "MET": 0,
    "GIS": 0,
    "IQV": 0,
    "EXC": 0,
    "WELL": 0,
    "DXCM": 0,
    "HLT": 0,
    "ON": 0,
    "COF": 0,
    "PAYX": 0,
    "TFC": 0,
    "BIIB": 0,
        "O": 0,
    "FTNT": 0,
    "DOW": 0,
    "TRV": 0,
    "DLR": 0,
    "MRNA": 0,
    "CPRT": 0,
    "ODFL": 0,
    "DHI": 0,
    "YUM": 0,
    "SPG": 0,
    "CTSH": 0,
    "AME": 0,
    "BKR": 0,
    "SYY": 0,
    "A": 0,
    "CTVA": 0,
    "CNC": 0,
    "EL": 0,
    "AMP": 0,
    "CEG": 0,
    "HAL": 0,
    "OTIS": 0,
    "ROK": 0,
    "PRU": 0,
    "DD": 0,
    "KMI": 0,
    "VRSK": 0,
    "LHX": 0,
    "DG": 0,
    "FIS": 0,
    "CMI": 0,
    "CSGP": 0,
    "FAST": 0,
    "PPG": 0,
    "GPN": 0,
    "GWW": 0,
    "HSY": 0,
    "BK": 0,
    "XEL": 0,
    "DVN": 0,
    "EA": 0,
    "NEM": 0,
    "ED": 0,
    "URI": 0,
    "VICI": 0,
    "PEG": 0,
    "KR": 0,
    "RSG": 0,
    "LEN": 0,
    "PWR": 0,
    "WST": 0,
    "COR": 0,
    "OKE": 0,
    "VMC": 0,
    "KDP": 0,
    "WBD": 0,
    "ACGL": 0,
    "ALL": 0,
    "IR": 0,
    "CDW": 0,
    "FANG": 0,
    "MLM": 0,
    "PCG": 0,
    "DAL": 0,
    "EXR": 0,
    "FTV": 0,
    "AWK": 0,
    "IT": 0,
    "KHC": 0,
    "GEHC": 0,
    "WEC": 0,
    "HPQ": 0,
    "EIX": 0,
    "CBRE": 0,
    "APTV": 0,
    "ANSS": 0,
    "MTD": 0,
    "DLTR": 0,
    "AVB": 0,
    "ILMN": 0,
    "ALGN": 0,
    "LYB": 0,
    "TROW": 0,
    "GLW": 0,
    "EFX": 0,
    "WY": 0,
    "ZBH": 0,
    "XYL": 0,
    "SBAC": 0,
    "RMD": 0,
    "TSCO": 0,
    "EBAY": 0,
    "KEYS": 0,
    "CHD": 0,
    "STT": 0,
    "DFS": 0,
    "HIG": 0,
    "ALB": 0,
    "STE": 0,
     "ES": 0,
    "TTWO": 0,
    "MPWR": 0,
    "CAH": 0,
    "EQR": 0,
    "RCL": 0,
    "WTW": 0,
    "HPE": 0,
    "DTE": 0,
    "GPC": 0,
    "BR": 0,
    "ULTA": 0,
    "FICO": 0,
    "CTRA": 0,
    "BAX": 0,
    "AEE": 0,
    "MTB": 0,
    "MKC": 0,
    "ETR": 0,
    "WAB": 0,
    "DOV": 0,
    "FE": 0,
    "RJF": 0,
    "INVH": 0,
    "FLT": 0,
    "CLX": 0,
    "TDY": 0,
    "TRGP": 0,
    "DRI": 0,
    "LH": 0,
    "HOLX": 0,
    "VRSN": 0,
    "MOH": 0,
    "LUV": 0,
    "PPL": 0,
    "ARE": 0,
    "NVR": 0,
    "COO": 0,
    "WBA": 0,
    "PHM": 0,
    "NDAQ": 0,
    "HWM": 0,
    "RF": 0,
    "CNP": 0,
    "IRM": 0,
    "LVS": 0,
    "FITB": 0,
    "EXPD": 0,
    "VTR": 0,
    "FSLR": 0,
    "PFG": 0,
    "BRO": 0,
    "J": 0,
    "IEX": 0,
    "BG": 0,
    "ATO": 0,
    "FDS": 0,
    "ENPH": 0,
    "MAA": 0,
    "CMS": 0,
    "IFF": 0,
    "BALL": 0,
    "SWKS": 0,
    "CINF": 0,
    "NTAP": 0,
    "STLD": 0,
    "UAL": 0,
    "WAT": 0,
    "OMC": 0,
    "TER": 0,
    "CCL": 0,
    "JBHT": 0,
    "MRO": 0,
    "TYL": 0,
    "HBAN": 0,
    "K": 0,
    "GRMN": 0,
    "CBOE": 0,
    "NTRS": 0,
    "TSN": 0,
    "AKAM": 0,
    "EG": 0,
    "ESS": 0,
    "EQT": 0,
    "TXT": 0,
    "EXPE": 0,
    "SJM": 0,
    "PTC": 0,
    "DGX": 0,
    "AVY": 0,
    "RVTY": 0,
    "BBY": 0,
    "CF": 0,
    "CAG": 0,
    "EPAM": 0,
    "AMCR": 0,
    "LW": 0,
    "PAYC": 0,
    "SNA": 0,
    "AXON": 0,
    "POOL": 0,
    "SYF": 0,
    "SWK": 0,
    "ZBRA": 0,
    "DPZ": 0,
    "PKG": 0,
    "CFG": 0,
    "LDOS": 0,
    "VTRS": 0,
    "PODD": 0,
    "LKQ": 0,
    "MOS": 0,
    "APA": 0,
    "EVRG": 0,
    "TRMB": 0,
    "MGM": 0,
    "NDSN": 0,
    "WDC": 0,
    "MAS": 0,
    "LNT": 0,
    "IPG": 0,
    "MTCH": 0,
    "STX": 0,
    "KMX": 0,
    "TECH": 0,
    "WRB": 0,
    "BFB": 0,
    "LYV": 0,
    "IP": 0,
    "UDR": 0,
    "AES": 0,
    "CE": 0,
    "INCY": 0,
    "L": 0,
    "TAP": 0,
    "GEN": 0,
    "CPT": 0,
    "KIM": 0,
    "JKHY": 0,
    "HRL": 0,
    "HST": 0,
    "FMC": 0,
    "CZR": 0,
    "PEAK": 0,
    "CDAY": 0,
    "PNR": 0,
    "NI": 0,
    "CHRW": 0,
    "HSIC": 0,
    "CRL": 0,
    "REG": 0,
    "QRVO": 0,
    "TFX": 0,
    "KEY": 0,
    "GL": 0,
    "EMN": 0,
    "WYNN": 0,
    "ALLE": 0,
    "AAL": 0,
    "FFIV": 0,
    "BWA": 0,
    "BXP": 0,
    "MKTX": 0,
    "ROL": 0,
    "JNPR": 0,
    "PNW": 0,
    "ETSY": 0,
    "BLDR": 0,
    "FOXA": 0,
    "AOS": 0,
    "HAS": 0,
    "HII": 0,
    "NRG": 0,
    "CPB": 0,
    "UHS": 0,
    "BIO": 0,
    "WRK": 0,
    "RHI": 0,
    "CTLT": 0,
    "GEV": 0,
    "BBWI": 0,
    "NWSA": 0,
    "TPR": 0,
    "PARA": 0,
    "SMCI": 0,
    "BEN": 0,
    "AIZ": 0,
    "NCLH": 0,
    "GNRC": 0,
    "FRT": 0,
    "IVZ": 0,
    "SOLV": 0,
    "CMA": 0,
    "DVA": 0,
    "JBL": 0,
    "HUBB": 0,
    "DECK": 0,
    "UBER": 0,
    "MHK": 0,
    "RL": 0,
    "VLTO": 0,
    "FOX": 0,
    "BX": 0,
    "ABNB": 0,
    "NWS": 0
}